// Generated by gencpp from file class_model/receiverCMD.msg
// DO NOT EDIT!


#ifndef CLASS_MODEL_MESSAGE_RECEIVERCMD_H
#define CLASS_MODEL_MESSAGE_RECEIVERCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace class_model
{
template <class ContainerAllocator>
struct receiverCMD_
{
  typedef receiverCMD_<ContainerAllocator> Type;

  receiverCMD_()
    : cmd()  {
    }
  receiverCMD_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::class_model::receiverCMD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::class_model::receiverCMD_<ContainerAllocator> const> ConstPtr;

}; // struct receiverCMD_

typedef ::class_model::receiverCMD_<std::allocator<void> > receiverCMD;

typedef boost::shared_ptr< ::class_model::receiverCMD > receiverCMDPtr;
typedef boost::shared_ptr< ::class_model::receiverCMD const> receiverCMDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::class_model::receiverCMD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::class_model::receiverCMD_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::class_model::receiverCMD_<ContainerAllocator1> & lhs, const ::class_model::receiverCMD_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::class_model::receiverCMD_<ContainerAllocator1> & lhs, const ::class_model::receiverCMD_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace class_model

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::class_model::receiverCMD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::class_model::receiverCMD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::class_model::receiverCMD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::class_model::receiverCMD_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::class_model::receiverCMD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::class_model::receiverCMD_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::class_model::receiverCMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43a54fa49066cddcf148717d9d4a6353";
  }

  static const char* value(const ::class_model::receiverCMD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43a54fa49066cddcULL;
  static const uint64_t static_value2 = 0xf148717d9d4a6353ULL;
};

template<class ContainerAllocator>
struct DataType< ::class_model::receiverCMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "class_model/receiverCMD";
  }

  static const char* value(const ::class_model::receiverCMD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::class_model::receiverCMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# receiverCMD.msg\n"
"\n"
"# Command message\n"
"string cmd\n"
;
  }

  static const char* value(const ::class_model::receiverCMD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::class_model::receiverCMD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct receiverCMD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::class_model::receiverCMD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::class_model::receiverCMD_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLASS_MODEL_MESSAGE_RECEIVERCMD_H
